/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package spacestationapp;

import javax.swing.DefaultComboBoxModel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author 1710809
 */
public class ManageStationForm extends javax.swing.JFrame {
    DefaultTableModel shipsInOuterSpaceModel;
    //DefaultTableModel shipsOnSelectedStationModel;
    DefaultComboBoxModel<SpaceshipStation> stationsBoxModel;
    
    public ManageStationForm() {
        initComponents();
        
        shipsInOuterSpaceModel = (DefaultTableModel) shipsInOuterSpaceTable.getModel();
        //shipsOnSelectedStationModel = (DefaultTableModel) shipsOnCurrentStationTable.getModel();
        stationsBoxModel = new DefaultComboBoxModel<SpaceshipStation>();
        
        for (int i = 0; i < Data.shipsInOuterSpaceList.size(); i++)
        {
            String shipInSpaceName = Data.shipsInOuterSpaceList.get(i).shipName;    
            int shipInSpaceWeight = Data.shipsInOuterSpaceList.get(i).shipWeight;
            String shipInSpacePilot = Data.shipsInOuterSpaceList.get(i).pilot;
            Object[] data = {shipInSpaceName, shipInSpaceWeight, shipInSpacePilot};
            shipsInOuterSpaceModel.insertRow(i, data);
        }
               
        for (int i = 0; i < Data.stationsList.size(); i++) 
        {
            stationsBoxModel.addElement(Data.stationsList.get(i));
        }
        stationsListComboBox.setModel(stationsBoxModel);
        
//        for (int i = 0; i < Data.stationsList.get(i).shipsOnStation.size(); i++)
//        {
//            //String shipOnStationName = Data.stationsList.get(i).shipsOnStation.get(i).shipName; 
//            //String shipOnStationName = stationsListComboBox.getSelectedItem();
//            Object[] data = {shipOnStationName};
//            shipsOnSelectedStationModel.insertRow(i, data);
//        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        changeStationNameLabel = new javax.swing.JLabel();
        choseStationLabel = new javax.swing.JLabel();
        changeWeightLimitLabel = new javax.swing.JLabel();
        changeShipsLimitLabel = new javax.swing.JLabel();
        stationsListComboBox = new javax.swing.JComboBox<>();
        changeNameTextField = new javax.swing.JTextField();
        changeWeightLimitTextField = new javax.swing.JTextField();
        changeShipsLimitTextField = new javax.swing.JTextField();
        acceptChangesButton = new javax.swing.JButton();
        quitButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        shipsInOuterSpaceTable = new javax.swing.JTable();
        letInStationButton = new javax.swing.JButton();
        letOutOfStationButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        changeStationNameLabel.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        changeStationNameLabel.setText("Change Name");

        choseStationLabel.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        choseStationLabel.setText("Chose Station");

        changeWeightLimitLabel.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        changeWeightLimitLabel.setText("Change Weight Limit");

        changeShipsLimitLabel.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        changeShipsLimitLabel.setText("Change Ships Limit");

        stationsListComboBox.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N

        changeNameTextField.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N

        changeWeightLimitTextField.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        changeWeightLimitTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changeWeightLimitTextFieldActionPerformed(evt);
            }
        });

        changeShipsLimitTextField.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        changeShipsLimitTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changeShipsLimitTextFieldActionPerformed(evt);
            }
        });

        acceptChangesButton.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        acceptChangesButton.setText("Accept Changes");

        quitButton.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        quitButton.setText("Quit");
        quitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quitButtonActionPerformed(evt);
            }
        });

        shipsInOuterSpaceTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Ships In Space", "Weight", "Pilot"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Integer.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(shipsInOuterSpaceTable);

        letInStationButton.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        letInStationButton.setText("Let In");

        letOutOfStationButton.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        letOutOfStationButton.setText("Let Out");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(quitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(acceptChangesButton, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(changeWeightLimitLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(changeShipsLimitLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(changeStationNameLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(choseStationLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(letInStationButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(63, 63, 63)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(changeNameTextField, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(changeWeightLimitTextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                            .addComponent(stationsListComboBox, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(changeShipsLimitTextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                            .addComponent(letOutOfStationButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(78, 78, 78)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(63, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(choseStationLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(stationsListComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(changeStationNameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
                            .addComponent(changeNameTextField))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(changeWeightLimitLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(changeWeightLimitTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(changeShipsLimitLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(changeShipsLimitTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(letInStationButton, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(letOutOfStationButton, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(acceptChangesButton, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(52, 52, 52))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)))
                .addComponent(quitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void changeWeightLimitTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changeWeightLimitTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_changeWeightLimitTextFieldActionPerformed

    private void changeShipsLimitTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changeShipsLimitTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_changeShipsLimitTextFieldActionPerformed

    private void quitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quitButtonActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_quitButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManageStationForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManageStationForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManageStationForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManageStationForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManageStationForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton acceptChangesButton;
    private javax.swing.JTextField changeNameTextField;
    private javax.swing.JLabel changeShipsLimitLabel;
    private javax.swing.JTextField changeShipsLimitTextField;
    private javax.swing.JLabel changeStationNameLabel;
    private javax.swing.JLabel changeWeightLimitLabel;
    private javax.swing.JTextField changeWeightLimitTextField;
    private javax.swing.JLabel choseStationLabel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton letInStationButton;
    private javax.swing.JButton letOutOfStationButton;
    private javax.swing.JButton quitButton;
    private javax.swing.JTable shipsInOuterSpaceTable;
    private javax.swing.JComboBox<SpaceshipStation> stationsListComboBox;
    // End of variables declaration//GEN-END:variables
}
